export { Header } from "./Header";
export { Hero } from "./Hero";
export { Benefits } from "./Benefits";
export { AllinWasiMeaning } from "./AllinWasiMeaning";
export { LandlordCTA } from "./LandlordCTA";
export { TenantCTA } from "./TenantCTA";
export { Testimonials } from "./Testimonials";
export { LegalNotice } from "./LegalNotice";
export { Footer } from "./Footer";
